export const UTILITY_CLASSES: { [key: string]: string } = {
	// Background colors
	"bg-red": "background-color: var(--color-red);",
	"bg-orange": "background-color: var(--color-orange);",
	"bg-yellow": "background-color: var(--color-yellow);",
	"bg-green": "background-color: var(--color-green);",
	"bg-cyan": "background-color: var(--color-cyan);",
	"bg-blue": "background-color: var(--color-blue);",
	"bg-purple": "background-color: var(--color-purple);",
	"bg-pink": "background-color: var(--color-pink);",
	"bg-accent": "background-color: var(--color-accent);",
	"bg-base": "background-color: var(--color-base-20);",
	"bg-transparent": "background-color: transparent;",

	// Border colors and styles
	brdr: "border: 1px solid;",
	"brdr-2": "border: 2px solid;",
	"brdr-4": "border: 4px solid;",

	"brdr-l": "border-left: 1px solid;",
	"brdr-l-2": "border-left: 2px solid;",
	"brdr-l-4": "border-left: 4px solid;",

	"brdr-r": "border-right: 1px solid;",
	"brdr-r-2": "border-right: 2px solid;",
	"brdr-r-4": "border-right: 4px solid;",

	"brdr-t": "border-top: 1px solid;",
	"brdr-t-2": "border-top: 2px solid;",
	"brdr-t-4": "border-top: 4px solid;",

	"brdr-red": "border-color: var(--color-red);",
	"brdr-orange": "border-color: var(--color-orange);",
	"brdr-yellow": "border-color: var(--color-yellow);",
	"brdr-green": "border-color: var(--color-green);",
	"brdr-cyan": "border-color: var(--color-cyan);",
	"brdr-blue": "border-color: var(--color-blue);",
	"brdr-purple": "border-color: var(--color-purple);",
	"brdr-pink": "border-color: var(--color-pink);",
	"brdr-accent": "border-color: var(--color-accent);",
	"brdr-base": "border-color: var(--color-base-20);",
	"brdr-white": "border-color: white;",
	"brdr-black": "border-color: black;",

	"brdr-solid": "border-style: solid;",
	"brdr-dash": "border-style: dashed;",

	// Padding
	"p-0": "padding: 0;",
	"p-2": "padding: var(--size-2-1);",
	"p-4": "padding: var(--size-2-2);",
	"p-6": "padding: var(--size-2-3);",
	"p-8": "padding: var(--size-4-2);",
	"p-12": "padding: var(--size-4-3);",
	"p-16": "padding: var(--size-4-4);",
	"p-20": "padding: var(--size-4-5);",
	"p-24": "padding: var(--size-4-6);",
	"p-32": "padding: var(--size-4-8);",
	"p-36": "padding: var(--size-4-9);",
	"p-48": "padding: var(--size-4-12);",
	"p-64": "padding: var(--size-4-16);",
	"p-72": "padding: var(--size-4-18);",

	"px-2": "padding-left: var(--size-2-1); padding-right: var(--size-2-1);",
	"px-4": "padding-left: var(--size-2-2); padding-right: var(--size-2-2);",
	"px-6": "padding-left: var(--size-2-3); padding-right: var(--size-2-3);",
	"px-8": "padding-left: var(--size-4-2); padding-right: var(--size-4-2);",
	"px-12": "padding-left: var(--size-4-3); padding-right: var(--size-4-3);",
	"px-16": "padding-left: var(--size-4-4); padding-right: var(--size-4-4);",
	"px-20": "padding-left: var(--size-4-5); padding-right: var(--size-4-5);",
	"px-24": "padding-left: var(--size-4-6); padding-right: var(--size-4-6);",
	"px-32": "padding-left: var(--size-4-8); padding-right: var(--size-4-8);",
	"px-36": "padding-left: var(--size-4-9); padding-right: var(--size-4-9);",
	"px-48": "padding-left: var(--size-4-12); padding-right: var(--size-4-12);",
	"px-64": "padding-left: var(--size-4-16); padding-right: var(--size-4-16);",
	"px-72": "padding-left: var(--size-4-18); padding-right: var(--size-4-18);",

	"py-2": "padding-top: var(--size-2-1); padding-bottom: var(--size-2-1);",
	"py-4": "padding-top: var(--size-2-2); padding-bottom: var(--size-2-2);",
	"py-6": "padding-top: var(--size-2-3); padding-bottom: var(--size-2-3);",
	"py-8": "padding-top: var(--size-4-2); padding-bottom: var(--size-4-2);",
	"py-12": "padding-top: var(--size-4-3); padding-bottom: var(--size-4-3);",
	"py-16": "padding-top: var(--size-4-4); padding-bottom: var(--size-4-4);",
	"py-20": "padding-top: var(--size-4-5); padding-bottom: var(--size-4-5);",
	"py-24": "padding-top: var(--size-4-6); padding-bottom: var(--size-4-6);",
	"py-32": "padding-top: var(--size-4-8); padding-bottom: var(--size-4-8);",
	"py-36": "padding-top: var(--size-4-9); padding-bottom: var(--size-4-9);",
	"py-48": "padding-top: var(--size-4-12); padding-bottom: var(--size-4-12);",
	"py-64": "padding-top: var(--size-4-16); padding-bottom: var(--size-4-16);",
	"py-72": "padding-top: var(--size-4-18); padding-bottom: var(--size-4-18);",

	// Margin
	"m-0": "margin: 0;",
	"m-2": "margin: var(--size-2-1);",
	"m-4": "margin: var(--size-2-2);",
	"m-6": "margin: var(--size-2-3);",
	"m-8": "margin: var(--size-4-2);",
	"m-12": "margin: var(--size-4-3);",
	"m-16": "margin: var(--size-4-4);",
	"m-20": "margin: var(--size-4-5);",
	"m-24": "margin: var(--size-4-6);",
	"m-32": "margin: var(--size-4-8);",
	"m-36": "margin: var(--size-4-9);",
	"m-48": "margin: var(--size-4-12);",
	"m-64": "margin: var(--size-4-16);",
	"m-72": "margin: var(--size-4-18);",

	"mx-0": "margin-left: 0; margin-right: 0;",
	"mx-2": "margin-left: var(--size-2-1); margin-right: var(--size-2-1);",
	"mx-4": "margin-left: var(--size-2-2); margin-right: var(--size-2-2);",
	"mx-6": "margin-left: var(--size-2-3); margin-right: var(--size-2-3);",
	"mx-8": "margin-left: var(--size-4-2); margin-right: var(--size-4-2);",
	"mx-12": "margin-left: var(--size-4-3); margin-right: var(--size-4-3);",
	"mx-16": "margin-left: var(--size-4-4); margin-right: var(--size-4-4);",
	"mx-20": "margin-left: var(--size-4-5); margin-right: var(--size-4-5);",
	"mx-24": "margin-left: var(--size-4-6); margin-right: var(--size-4-6);",
	"mx-32": "margin-left: var(--size-4-8); margin-right: var(--size-4-8);",
	"mx-36": "margin-left: var(--size-4-9); margin-right: var(--size-4-9);",
	"mx-48": "margin-left: var(--size-4-12); margin-right: var(--size-4-12);",
	"mx-64": "margin-left: var(--size-4-16); margin-right: var(--size-4-16);",
	"mx-72": "margin-left: var(--size-4-18); margin-right: var(--size-4-18);",

	"my-0": "margin-top: 0; margin-bottom: 0;",
	"my-2": "margin-top: var(--size-2-1); margin-bottom: var(--size-2-1);",
	"my-4": "margin-top: var(--size-2-2); margin-bottom: var(--size-2-2);",
	"my-6": "margin-top: var(--size-2-3); margin-bottom: var(--size-2-3);",
	"my-8": "margin-top: var(--size-4-2); margin-bottom: var(--size-4-2);",
	"my-12": "margin-top: var(--size-4-3); margin-bottom: var(--size-4-3);",
	"my-16": "margin-top: var(--size-4-4); margin-bottom: var(--size-4-4);",
	"my-20": "margin-top: var(--size-4-5); margin-bottom: var(--size-4-5);",
	"my-24": "margin-top: var(--size-4-6); margin-bottom: var(--size-4-6);",
	"my-32": "margin-top: var(--size-4-8); margin-bottom: var(--size-4-8);",
	"my-36": "margin-top: var(--size-4-9); margin-bottom: var(--size-4-9);",
	"my-48": "margin-top: var(--size-4-12); margin-bottom: var(--size-4-12);",
	"my-64": "margin-top: var(--size-4-16); margin-bottom: var(--size-4-16);",
	"my-72": "margin-top: var(--size-4-18); margin-bottom: var(--size-4-18);",

	"ml-auto": "margin-left: auto;",
	"mr-auto": "margin-right: auto;",
	"mx-auto": "margin-left: auto; margin-right: auto;",
	"my-auto": "margin-top: auto; margin-bottom: auto;",

	// Border radius
	rad: "border-radius: var(--radius-s);",
	"rad-md": "border-radius: var(--radius-m);",
	"rad-lg": "border-radius: var(--radius-l);",
	"rad-xl": "border-radius: var(--radius-xl);",
	"rad-full": "border-radius: 50%;",

	// Text colors
	"txt-normal": "color: var(--text-normal);",
	"txt-red": "color: var(--color-red);",
	"txt-orange": "color: var(--color-orange);",
	"txt-yellow": "color: var(--color-yellow);",
	"txt-green": "color: var(--color-green);",
	"txt-cyan": "color: var(--color-cyan);",
	"txt-blue": "color: var(--color-blue);",
	"txt-purple": "color: var(--color-purple);",
	"txt-pink": "color: var(--color-pink);",
	"txt-accent": "color: var(--text-accent);",
	"txt-base": "color: var(--color-base-20);",
	"txt-muted": "color: var(--text-muted);",
	"txt-faint": "color: var(--text-faint);",
	"txt-success": "color: var(--text-success);",
	"txt-warning": "color: var(--text-warning);",
	"txt-error": "color: var(--text-error);",
	"txt-white": "color: white;",

	// Text weight
	"fnt-thin": "font-weight: 100;",
	"fnt-extralight": "font-weight: 200;",
	"fnt-light": "font-weight: 300;",
	"fnt-normal": "font-weight: 400;",
	"fnt-medium": "font-weight: 500;",
	"fnt-semibold": "font-weight: 600;",
	"fnt-bold": "font-weight: 700;",
	"fnt-extrabold": "font-weight: 800;",
	"fnt-black": "font-weight: 900;",

	// Text decoration
	italic: "font-style: italic;",
	underline: "text-decoration: underline;",
	"line-through": "text-decoration: line-through;",
	uppercase: "text-transform: uppercase;",
	lowercase: "text-transform: lowercase;",

	// Text alignment
	"txt-left": "text-align: left;",
	"txt-center": "text-align: center;",
	"txt-right": "text-align: right;",

	// Text size
	"txt-size": "font-size: var(--font-text-size);",
	"txt-2xs": "font-size: var(--font-smallest);",
	"txt-xs": "font-size: var(--font-smaller);",
	"txt-sm": "font-size: var(--font-small);",
	"txt-md": "font-size: 1em;",
	"txt-lg": "font-size: 1.125em;",
	"txt-xl": "font-size: 1.25em;",
	"txt-2xl": "font-size: 1.5em;",
	"txt-3xl": "font-size: 1.875em;",
	"txt-4xl": "font-size: 2.25em;",
	"txt-5xl": "font-size: 3em;",
	"txt-ui-xs": "font-size: var(--font-ui-smaller);",
	"txt-ui-sm": "font-size: var(--font-ui-small);",
	"txt-ui-md": "font-size: var(--font-ui-medium);",
	"txt-ui-lg": "font-size: var(--font-ui-large);",

	// Fonts
	"fnt-ui": "font-family: var(--font-interface-theme);",
	"fnt-theme": "font-family: var(--font-text-theme);",
	"fnt-mono": "font-family: var(--font-monospace-theme);",

	// Display and layout
	blck: "display: block;",
	inln: "display: inline;",
	"inln-blck": "display: inline-block;",
	flx: "display: flex;",
	grd: "display: grid;",
	hide: "display: none;",

	// Flexbox
	"flx-col": "flex-direction: column;",
	"flx-row": "flex-direction: row;",

	"aln-center": "align-items: center;",
	"aln-start": "align-items: flex-start;",
	"aln-end": "align-items: flex-end;",
	"aln-baseline": "align-items: baseline;",
	"aln-stretch": "align-items: stretch;",

	"jst-center": "justify-content: center;",
	"jst-between": "justify-content: space-between;",
	"jst-around": "justify-content: space-around;",
	"jst-start": "justify-content: flex-start;",
	"jst-end": "justify-content: flex-end;",

	"gp-2": "gap: var(--size-2-1);",
	"gp-4": "gap: var(--size-4-1);",
	"gp-6": "gap: var(--size-2-3);",
	"gp-8": "gap: var(--size-4-2);",
	"gp-12": "gap: var(--size-4-3);",
	"gp-16": "gap: var(--size-4-4);",
	"gp-20": "gap: var(--size-4-5);",
	"gp-24": "gap: var(--size-4-6);",
	"gp-32": "gap: var(--size-4-8);",
	"gp-36": "gap: var(--size-4-9);",
	"gp-40": "gap: var(--size-4-10);",
	"gp-48": "gap: var(--size-4-12);",
	"gp-64": "gap: var(--size-4-16);",
	"gp-72": "gap: var(--size-4-18);",

	// Grid columns
	"grd-cls-1": "grid-template-columns: repeat(1, 1fr);",
	"grd-cls-2": "grid-template-columns: repeat(2, 1fr);",
	"grd-cls-3": "grid-template-columns: repeat(3, 1fr);",
	"grd-cls-4": "grid-template-columns: repeat(4, 1fr);",
	"grd-cls-5": "grid-template-columns: repeat(5, 1fr);",
	"grd-cls-6": "grid-template-columns: repeat(6, 1fr);",
	"grd-cls-7": "grid-template-columns: repeat(7, 1fr);",
	"grd-cls-8": "grid-template-columns: repeat(8, 1fr);",
	"grd-cls-9": "grid-template-columns: repeat(9, 1fr);",
	"grd-cls-10": "grid-template-columns: repeat(10, 1fr);",
	"grd-cls-11": "grid-template-columns: repeat(11, 1fr);",
	"grd-cls-12": "grid-template-columns: repeat(12, 1fr);",

	// Grid rows
	"grd-rws-1": "grid-template-rows: repeat(1, 1fr);",
	"grd-rws-2": "grid-template-rows: repeat(2, 1fr);",
	"grd-rws-3": "grid-template-rows: repeat(3, 1fr);",
	"grd-rws-4": "grid-template-rows: repeat(4, 1fr);",
	"grd-rws-5": "grid-template-rows: repeat(5, 1fr);",
	"grd-rws-6": "grid-template-rows: repeat(6, 1fr);",

	// Fractional layouts
	"grd-1-3": "grid-template-columns: 1fr 3fr;",
	"grd-2-3": "grid-template-columns: 2fr 3fr;",
	"grd-1-4": "grid-template-columns: 1fr 4fr;",
	"grd-3-4": "grid-template-columns: 3fr 4fr;",

	"grd-2-1-1": "grid-template-columns: 2fr 1fr 1fr;",
	"grd-1-2-1": "grid-template-columns: 1fr 2fr 1fr;",
	"grd-1-1-2": "grid-template-columns: 1fr 1fr 2fr;",
	"grd-2-2-1": "grid-template-columns: 2fr 2fr 1fr;",
	"grd-1-2-2": "grid-template-columns: 1fr 2fr 2fr;",
	"grd-2-1-2": "grid-template-columns: 2fr 1fr 2fr;",

	"grd-2-1-1-1": "grid-template-columns: 2fr 1fr 1fr 1fr;",
	"grd-1-2-1-1": "grid-template-columns: 1fr 2fr 1fr 1fr;",
	"grd-1-1-2-1": "grid-template-columns: 1fr 1fr 2fr 1fr;",
	"grd-1-1-1-2": "grid-template-columns: 1fr 1fr 1fr 2fr;",

	// Auto layouts
	"grd-cols-auto": "grid-template-columns: auto;",
	"grd-cols-auto-1fr": "grid-template-columns: auto 1fr;",
	"grd-cols-1fr-auto": "grid-template-columns: 1fr auto;",
	"grd-cols-minmax": "grid-template-columns: minmax(0, 1fr) minmax(0, 2fr);",

	// Row and column gaps
	"r-gp-2": "row-gap: var(--size-2-1);",
	"r-gp-4": "row-gap: var(--size-4-1);",
	"r-gp-6": "row-gap: var(--size-2-3);",
	"r-gp-8": "row-gap: var(--size-4-2);",
	"r-gp-12": "row-gap: var(--size-4-3);",
	"r-gp-16": "row-gap: var(--size-4-4);",
	"r-gp-20": "row-gap: var(--size-4-5);",
	"r-gp-24": "row-gap: var(--size-4-6);",
	"r-gp-32": "row-gap: var(--size-4-8);",
	"r-gp-36": "row-gap: var(--size-4-9);",
	"r-gp-40": "row-gap: var(--size-4-10);",
	"r-gp-48": "row-gap: var(--size-4-12);",
	"r-gp-64": "row-gap: var(--size-4-16);",
	"r-gp-72": "row-gap: var(--size-4-18);",

	"c-gp-2": "column-gap: var(--size-2-1);",
	"c-gp-4": "column-gap: var(--size-4-1);",
	"c-gp-6": "column-gap: var(--size-2-3);",
	"c-gp-8": "column-gap: var(--size-4-2);",
	"c-gp-12": "column-gap: var(--size-4-3);",
	"c-gp-16": "column-gap: var(--size-4-4);",
	"c-gp-20": "column-gap: var(--size-4-5);",
	"c-gp-24": "column-gap: var(--size-4-6);",
	"c-gp-32": "column-gap: var(--size-4-8);",
	"c-gp-36": "column-gap: var(--size-4-9);",
	"c-gp-40": "column-gap: var(--size-4-10);",
	"c-gp-48": "column-gap: var(--size-4-12);",
	"c-gp-64": "column-gap: var(--size-4-16);",
	"c-gp-72": "column-gap: var(--size-4-18);",

	// Width and height
	"w-full": "width: 100%;",
	"h-auto": "height: auto;",
	"h-full": "height: 100%;",
	"max-w-full": "max-width: 100%;",
	"max-h-full": "max-height: 100%;",
	"min-w-0": "min-width: 0;",
	"min-h-0": "min-height: 0;",

	// Opacity
	"opac-0": "opacity: 0;",
	"opac-25": "opacity: 0.25;",
	"opac-50": "opacity: 0.5;",
	"opac-75": "opacity: 0.75;",
	"opac-100": "opacity: 1;",

	// Gradients
	"grad-accent":
		"background: linear-gradient(135deg, var(--color-accent), var(--color-accent-2));",
	"grad-base":
		"background: linear-gradient(135deg, var(--color-base-20), var(--color-base-30));",

	// Shadow
	shad: "box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);",
	"shad-md": "box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);",
	"shad-lg": "box-shadow: 0 10px 15px rgba(0, 0, 0, 0.1);",

	// Transitions
	trans: "transition: all 0.2s ease;",
	"trans-fast": "transition: all 0.1s ease;",
	"trans-slow": "transition: all 0.3s ease;",

	// Icon Sizes
	"icn-xs": "font-size: var(--icon-xs);",
	"icn-sm": "font-size: var(--icon-s);",
	"icn-md": "font-size: var(--icon-m);",
	"icn-lg": "font-size: var(--icon-l);",
	"icn-xl": "font-size: var(--icon-xl);",

	// Layers
	"z-top": "z-index: 1000;",
	"z-middle": "z-index: 500;",
	"z-bottom": "z-index: 0;",

	// Line height
	"lne-hght": "line-height: var(--line-height-normal);",
	"lne-hght-sm": "line-height: var(--line-height-tight);",
};
